---
abstract: 'An interface to a search engine index of pages crawled by WWW::3172::Crawler'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  Dancer::Test: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-3172-SearchEngine
no_index:
  directory:
    - corpus
requires:
  Dancer: 0
  Dancer::Plugin::Database: 0
  HTML::Entities: 0
  Lingua::Stem::Snowball: 0
  Lingua::StopWords: 0
  List::MoreUtils: 0
  Text::Unidecode: 0
  WWW::Form: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/WWW-3172-SearchEngine/issues
  repository: git://github.com/doherty/WWW-3172-SearchEngine.git
version: 0.001
